"use client";

import { api } from "@uni-exam-sys/backend/convex/_generated/api";
import { useQuery } from "convex/react";
import { Calendar, Loader2 } from "lucide-react";
import { useMemo, useState } from "react";

import { PageHeader } from "@/components/dashboard/kpi";
import { useMe } from "@/components/dashboard/dashboard-layout-shell";

import { Badge } from "@uni-exam-sys/ui/components/badge";
import { Input } from "@uni-exam-sys/ui/components/input";
import { ScrollArea } from "@uni-exam-sys/ui/components/scroll-area";
import { Separator } from "@uni-exam-sys/ui/components/separator";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@uni-exam-sys/ui/components/table";

export default function MyTimetablePage() {
  const me = useMe();
  const [search, setSearch] = useState("");

  const data = useQuery(api.dashboard.studentDashboard, me.role === "student" ? {} : "skip");

  const rows = useMemo(() => {
    if (!data?.timetable) return [];
    if (!search.trim()) return data.timetable;
    const term = search.trim().toLowerCase();
    return data.timetable.filter(
      (r) =>
        (r.courseCode ?? "").toLowerCase().includes(term) ||
        (r.courseName ?? "").toLowerCase().includes(term) ||
        (r.roomName ?? "").toLowerCase().includes(term),
    );
  }, [data, search]);

  if (me.role !== "student") {
    return (
      <div className="rounded-md border bg-card p-6 text-sm text-muted-foreground">
        Only students have a personal exam timetable.
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <PageHeader
        title="My Timetable"
        description="Your scheduled exams, rooms, and seats."
      />

      {data === undefined ? (
        <div className="flex items-center gap-2 p-6 text-xs text-muted-foreground">
          <Loader2 className="size-3.5 animate-spin" /> Loading…
        </div>
      ) : data === null ? (
        <div className="rounded-md border bg-card p-6 text-sm text-muted-foreground">
          Your student profile isn&apos;t linked yet. Contact your admin.
        </div>
      ) : (
        <>
          <div className="grid gap-3 sm:grid-cols-3">
            <div className="rounded-md border bg-card p-3">
              <p className="text-[11px] uppercase text-muted-foreground">Program</p>
              <p className="mt-1 text-sm font-medium">{data.program?.name ?? "—"}</p>
            </div>
            <div className="rounded-md border bg-card p-3">
              <p className="text-[11px] uppercase text-muted-foreground">Fee status</p>
              <p className="mt-1 text-sm font-medium">
                <Badge
                  variant={data.feeStatus.status === "cleared" ? "default" : "destructive"}
                  className="text-[10px] capitalize"
                >
                  {data.feeStatus.status}
                </Badge>
              </p>
            </div>
            <div className="rounded-md border bg-card p-3">
              <p className="text-[11px] uppercase text-muted-foreground">Exams</p>
              <p className="mt-1 text-sm font-medium">{data.timetable.length}</p>
            </div>
          </div>

          <div className="rounded-md border bg-card p-3">
            <Input
              value={search}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) => setSearch(e.target.value)}
              placeholder="Filter by course or room…"
              className="h-8 text-xs"
            />
          </div>

          <div className="rounded-md border bg-card">
            <div className="flex items-center gap-2 p-4">
              <Calendar className="size-4 text-primary" />
              <h2 className="text-sm font-semibold">Exam schedule</h2>
            </div>
            <Separator />
            {rows.length === 0 ? (
              <div className="p-6 text-xs text-muted-foreground">
                No exams scheduled yet. Seating must be generated by your admin before exams
                appear here.
              </div>
            ) : (
              <ScrollArea className="max-h-[60vh]">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Date</TableHead>
                      <TableHead>Time</TableHead>
                      <TableHead>Course</TableHead>
                      <TableHead>Room</TableHead>
                      <TableHead>Seat</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {rows.map((r, i) => (
                      <TableRow key={i}>
                        <TableCell className="text-xs font-medium">{r.examDate}</TableCell>
                        <TableCell className="text-[11px] text-muted-foreground">
                          {r.startTime}–{r.endTime}
                        </TableCell>
                        <TableCell>
                          <div className="flex flex-col">
                            <span className="text-xs font-medium">{r.courseCode}</span>
                            <span className="text-[10px] text-muted-foreground">{r.courseName}</span>
                          </div>
                        </TableCell>
                        <TableCell className="text-xs">{r.roomName}</TableCell>
                        <TableCell>
                          <Badge variant="secondary" className="text-[10px]">
                            {r.seatNumber}
                          </Badge>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </ScrollArea>
            )}
          </div>
        </>
      )}
    </div>
  );
}
